#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// Run a motor forward for 1 second
	writeDebugStreamLine("Start Forward");
	// motor[motorD] = 100;
	// wait1Msec(1000);
	writeDebugStreamLine("Done Forward");

	// Wait for 2 seconds
	wait1Msec(2000);

	// Run motor in reverse for 1 second
	writeDebugStreamLine("Start Reverse");
	// motor[motorD] = 100;
	// wait1Msec(1000);
	writeDebugStreamLine("Done Reverse");

}
